Spacecraft Control Bundle: fsw_star_catalog Class Reference
fsw_star_catalog Class Reference
Ephemeris, Catalog, and Database Modules
Star catalog processing.
#include <fsw_star_catalog.h>
Public Member Functions
fsw_star_catalog (const char *mod_name)
void initialize_data ()
Create data and request the FSW_STAR_CATALOG_TRIGGER.
void initialize_data_requests ()
Data requests from other modules.
void initialize ()
void handle_event (int code)
The star unit vectors are updated annually.
Protected Member Functions
bool initialize_star_catalog ()
Initialize the catalog.
void update_unit_vectors ()
Updates unit vectors for new date.
Protected Attributes
Inputs
CD_REQUEST_REF jd_ref
julian_date
Outputs
CD_CREATE_REF unit_vector_ref
CD_CREATE_REF visual_magnitude_ref
CD_CREATE_REF hip_ref
Parameters
CD_CREATE_REF filename_ref
File name.
Detailed Description
Star catalog processing.
This class provides unit vectors to the stars and magnitudes for each star. The star units vectors are calculated for the current date using the specified motion parameters. The star catalog is read from a file, which must have the name StarCatalog5122.txt and be in Model Libraries. The matrix in the file is M rows by 7 columns.
Member Function Documentation
handle_event()
void fsw_star_catalog::handle_event (int code)
The star unit vectors are updated annually.
References initialize_star_catalog(), jd_ref, julian_date, star_unit_vectors, star_visual_magnitude, sc_data::type, and update_unit_vectors().
initialize_data()
void fsw_star_catalog::initialize_data ()
Create data and request the FSW_STAR_CATALOG_TRIGGER.
References ephem_hipparcos_ids, filename_ref, FSW_STAR_CATALOG_TRIGGER, star_unit_vectors, star_visual_magnitude, and sc_data::type.
initialize_data_requests()
void fsw_star_catalog::initialize_data_requests ()
Data requests from other modules.
References jd_ref, julian_date, and sc_data::type.
initialize_star_catalog()
bool fsw_star_catalog::initialize_star_catalog () protected
Initialize the catalog.
Initialize the star catalog, update the star unit vectors to the current date, and set the unit vector and visual magnitude values.
The angular increment for removing stars that are "too close" is currently hard-coded.
References ephem_hipparcos_ids, filename_ref, star_unit_vectors, star_visual_magnitude, sc_data::type, and update_unit_vectors().
Referenced by handle_event().
update_unit_vectors()
void fsw_star_catalog::update_unit_vectors () protected
Updates unit vectors for new date.
Generate unit vectors from star_catalog, [ID vM rA dec parallax rV pMRA pMDec].
Accounts only for proper motion.
References jd_ref, and julian_date.
Referenced by handle_event(), and initialize_star_catalog().
Member Data Documentation
filename_ref
CD_CREATE_REF fsw_star_catalog::filename_ref protected
File name.
Referenced by initialize_data(), and initialize_star_catalog().
jd_ref
CD_REQUEST_REF fsw_star_catalog::jd_ref protected
julian_date
Referenced by handle_event(), initialize_data_requests(), and update_unit_vectors().
The documentation for this class was generated from the following files:
fsw_star_catalog.h
fsw_star_catalog.cc