var dir_d037c0415a64c51ad0fea9ceabf3ce85 =
[
    [ "AlfvenSpeed.m", "_alfven_speed_8m.html", "_alfven_speed_8m" ],
    [ "AtomicNumber.m", "_atomic_number_8m.html", "_atomic_number_8m" ],
    [ "BremsstrahlungFrequency.m", "_bremsstrahlung_frequency_8m.html", "_bremsstrahlung_frequency_8m" ],
    [ "BremsstrahlungWavelength.m", "_bremsstrahlung_wavelength_8m.html", "_bremsstrahlung_wavelength_8m" ],
    [ "BurnupTime.m", "_burnup_time_8m.html", "_burnup_time_8m" ],
    [ "CollisionTimes.m", "_collision_times_8m.html", "_collision_times_8m" ],
    [ "CoulombLog.m", "_coulomb_log_8m.html", "_coulomb_log_8m" ],
    [ "CoulombLogIons.m", "_coulomb_log_ions_8m.html", "_coulomb_log_ions_8m" ],
    [ "CrosssectionClassical.m", "_crosssection_classical_8m.html", "_crosssection_classical_8m" ],
    [ "CrossSectionFromRest.m", "_cross_section_from_rest_8m.html", "_cross_section_from_rest_8m" ],
    [ "CyclotronFrequency.m", "_cyclotron_frequency_8m.html", "_cyclotron_frequency_8m" ],
    [ "DebyeLength.m", "_debye_length_8m.html", "_debye_length_8m" ],
    [ "DHe3Reaction.m", "_d_he3_reaction_8m.html", "_d_he3_reaction_8m" ],
    [ "EffectiveCharge.m", "_effective_charge_8m.html", "_effective_charge_8m" ],
    [ "FusionReaction.m", "_fusion_reaction_8m.html", "_fusion_reaction_8m" ],
    [ "FusionReactionDD.m", "_fusion_reaction_d_d_8m.html", "_fusion_reaction_d_d_8m" ],
    [ "GasPressure.m", "_gas_pressure_8m.html", "_gas_pressure_8m" ],
    [ "GyroRadius.m", "_gyro_radius_8m.html", "_gyro_radius_8m" ],
    [ "IonCyclotronFrequency.m", "_ion_cyclotron_frequency_8m.html", "_ion_cyclotron_frequency_8m" ],
    [ "IonizationEnergy.m", "_ionization_energy_8m.html", "_ionization_energy_8m" ],
    [ "IonizationEnergyPlasma.m", "_ionization_energy_plasma_8m.html", "_ionization_energy_plasma_8m" ],
    [ "MaxwellianV.m", "_maxwellian_v_8m.html", "_maxwellian_v_8m" ],
    [ "NumberOfElectrons.m", "_number_of_electrons_8m.html", "_number_of_electrons_8m" ],
    [ "PhotonEnergy.m", "_photon_energy_8m.html", "_photon_energy_8m" ],
    [ "PlasmaConstant.m", "_plasma_constant_8m.html", "_plasma_constant_8m" ],
    [ "PlasmaFrequency.m", "_plasma_frequency_8m.html", "_plasma_frequency_8m" ],
    [ "PlasmaHeating.m", "_plasma_heating_8m.html", "_plasma_heating_8m" ],
    [ "PlasmaPressure.m", "_plasma_pressure_8m.html", "_plasma_pressure_8m" ],
    [ "PlasmaRadius.m", "_plasma_radius_8m.html", "_plasma_radius_8m" ],
    [ "PlasmaVolume.m", "_plasma_volume_8m.html", "_plasma_volume_8m" ],
    [ "PowerIonsToElectrons.m", "_power_ions_to_electrons_8m.html", "_power_ions_to_electrons_8m" ],
    [ "ReactionString.m", "_reaction_string_8m.html", "_reaction_string_8m" ],
    [ "SahaEquation.m", "_saha_equation_8m.html", "_saha_equation_8m" ],
    [ "SigmaV.m", "_sigma_v_8m.html", "_sigma_v_8m" ],
    [ "SynchrotronFrequency.m", "_synchrotron_frequency_8m.html", "_synchrotron_frequency_8m" ]
];