Spacecraft Control Framework: StdAtm Class Reference
StdAtm Class Reference
Space Environment
The standard atmosphere model.
#include <sc_stdatm.h>
Public Member Functions
void Initialize ()
Initialize from AtmData.txt.
void Initialize (const char fileName[])
Initialize from a fileName input.
void Update (double altitude)
Update the outputs.
double GetTemperature (void)
Return the temperature.
double GetPressure (void)
Return the pressure.
double GetDensity (void)
Return the density.
double GetSpeedOfSound (void)
Return the speed of sound.
double GetKinematicViscosity (void)
Return the kinematic viscosity.
Detailed Description
The standard atmosphere model.
Given the altitude, computes the temperature, pressure, density, speed of sound and kinematic viscosity.
Member Function Documentation
Initialize() [1/2]
void StdAtm::Initialize (void)
Initialize from AtmData.txt.
Initialize the model using a textfile AtmData.txt.
References Initialize().
Referenced by Initialize(), and AtmJ70ToGround::Initialize().
Initialize() [2/2]
void StdAtm::Initialize (const char fileName[])
Initialize from a fileName input.
Initialize the model using a textfile.
Parameters
fileName file name
References sc_warn().
Update()
void StdAtm::Update (double altitude)
Update the outputs.
Parameters
altitude
Referenced by AtmJ70ToGround::Update().