Spacecraft Control Framework: star Class Reference
star Class Reference
Optics
Star object.
#include <sc_star_catalog.h>
Public Member Functions
star ()
Default constructor.
star (int id, double VM, double right_ascension, double declination)
Constructor.
void set_motion_terms (double parallax, double pm_ascension, double pm_declination, double radialV)
Set the terms for stellar reduction.
ml_matrix CalculateVector (double jd_now, double jd_catalog) const
Calculate the star vector for a given date.
ml_matrix UnitVector (void) const
Calculate the unit vector from the catalog right ascension and declination.
int get_id () const
Get the star's (Hipparcos) id.
double get_ascension () const
Star right ascnension (rad)
double get_declination () const
Star declination (rad)
double get_magnitude () const
Visual magnitude ()
Detailed Description
Star object.
Includes the terms for correcting the star vector for proper motion.
Todo:
: account for full stellar reduction.
Constructor & Destructor Documentation
star()
star::star (int id, double VM, double right_ascension, double declination)
Constructor.
Parameters
id Integer ID of star
right_ascension Right ascension, radians
declination Declination, radians
VM Visual magnitude
Member Function Documentation
set_motion_terms()
void star::set_motion_terms (double parallax, double radialV, double pm_ascension, double pm_declination)
Set the terms for stellar reduction.
Parameters
parallax
radialV
pm_ascension
pm_declination
CalculateVector()
ml_matrix star::CalculateVector (double jd_now, double jd_catalog) const
Calculate the star vector for a given date.
The star unit vector using the right ascension and declination of date.
The default catalog date is for Hipparcos, 2448347.75, which is 1991.25
Parameters
jd_now Current Julian date
jd_catalog Catalog Julian date
Returns
Star unit vector corrected for proper motion
References PI, and ra_dec_to_u().
UnitVector()
ml_matrix star::UnitVector (void) const
Calculate the unit vector from the catalog right ascension and declination.
The star unit vector using the catalog right ascension and declination.
References ra_dec_to_u().
Referenced by near_matrix::near_matrix().
get_id()
int star::get_id () const
Get the star's (Hipparcos) id.
Get Hipparcos ID of star.
get_ascension()
double star::get_ascension () const
Star right ascnension (rad)
Get right ascension (rad)
get_declination()
double star::get_declination () const
Star declination (rad)
Get declination (rad)
get_magnitude()
double star::get_magnitude () const
Visual magnitude ()
Get magnitude.