Spacecraft Control Framework: aero_newtonian Class Reference
aero_newtonian Class Reference
Space Environment
Newtonian aerodynamic model.
#include <sc_aero_newtonian.h>
Public Member Functions
aero_newtonian (void)
Constructor.
void initialize (char *filename)
Initialize with a filename.
ml_matrix get_torque (void)
Return the torque.
ml_matrix get_force (void)
Return the force.
void update (const ml_matrix &u, const ml_matrix &center_of_mass, double rho, const ml_matrix &angle)
Update the values of torque and force.
ml_matrix newtonian_force_and_torque (const ml_matrix &normal, const ml_matrix &area, const ml_matrix &point, const ml_matrix &v, double rho, const ml_matrix &c)
Computes force and torque using the Newtonian approximation.
Detailed Description
Newtonian aerodynamic model.
This uses 4 matrices per surface. The organization of the data file is m Number of models [ x;y;z ] Rotation axis of model [ x;y;z ] Location of model with respect to the refernce [ v ] nx3 points [ f ] mx3 faces If the rotation axis is [0;0;0] then the model is assumed not to rotate relative to the core body.
Member Function Documentation
initialize()
void aero_newtonian::initialize (char * filename)
Initialize with a filename.
Initialize the model from an ASCII text data file.
References polygon_props(), sc_log(), and sc_warn().
update()
void aero_newtonian::update (const ml_matrix & u, const ml_matrix & center_of_mass, double rho, const ml_matrix & angle)
Update the values of torque and force.
Compute the force and torque.
Parameters
u Velocity vector in the ECI frame
center_of_mass Center of mass
rho Atmospheric density
angle Actuator angles
References au_to_q(), and newtonian_force_and_torque().
newtonian_force_and_torque()
ml_matrix aero_newtonian::newtonian_force_and_torque (const ml_matrix & normal, const ml_matrix & area, const ml_matrix & point, const ml_matrix & v, double rho, const ml_matrix & c)
Computes force and torque using the Newtonian approximation.
Good above Mach 4.
Parameters
normal Unit normal (3xn)
area Area (1xn)
point Location of centroid of each point (3xn)
v Velocity vector in the body frame (3x1)
rho Atmospheric density
c Center of mass
Returns
ml_matrix [force;torque].
Referenced by update().