Spacecraft Control Framework: AtmJ70ToGround Class Reference
AtmJ70ToGround Class Reference
Space Environment
Combined J70 and standard atmosphere model.
#include <sc_atmj70toground.h>
Public Member Functions
AtmJ70ToGround (void)
Default constructor.
bool Initialize (double jD, int kTiming, int kSigma, const char fileName[])
Initialize both the standard atmosphere and J70 models.
void Update (const ml_matrix &rECI, double jD)
Update the density model using a new ECI location and Julian date.
double GetTemperature (void)
Return the atmonspheric temperature in K.
double GetDensity (void)
Return the atmospheric density in kg/m^3.
double GetSpeedOfSound (void)
Return the speed of sound in m/s.
double GetKinematicViscosity (void)
Return the speed of sound in m/s.
double GetPressure (void)
Return the pressure in N/m^2.
Detailed Description
Combined J70 and standard atmosphere model.
The standard atmosphere is used up to 80 km, and the J70 model is used above. Uses the StdAtm and AtmJ70 classes.
Member Function Documentation
Initialize()
bool AtmJ70ToGround::Initialize (double jD, int kTiming, int kSigma, const char fileName[])
Initialize both the standard atmosphere and J70 models.
Parameters
jD Julian date
kSigma Error bars for J70. Can be 0, 1 or 2 (nominal, +2 sig, -2 sig)
kTiming Timing of solar cycle for J70, can be 0, 1 or 2 (nominal, early, late)
fileName Path to file containing J70 solar data
Returns
A flag indicating successful initialization of J70
References StdAtm::Initialize(), AtmJ70::Initialize(), and sc_warn().
Update()
void AtmJ70ToGround::Update (const ml_matrix & rECI, double jD)
Update the density model using a new ECI location and Julian date.
Parameters
rECI ECI position in km
jD Julian date
References AtmJ70::GetDensity(), StdAtm::GetDensity(), StdAtm::GetPressure(), StdAtm::GetSpeedOfSound(), AtmJ70::GetTemperature(), StdAtm::GetTemperature(), RADIUS_EARTH, StdAtm::Update(), and AtmJ70::Update().