Spacecraft Control Framework: sc_math.h File Reference
sc_math.h File Reference
Utilities
Math utility functions.
Functions
double golden_section (double RHS(double x, void *context), double a, double b, double tol, int maxIts, void *context)
Golden section minimization.
ml_matrix rk0 (ml_matrix RHS(ml_matrix x, double t, void *context), ml_matrix &x, double h, double t, void *context)
0th order Runge-Kutta integration algorithm with time as a RHS input
ml_matrix rk4 (ml_matrix RHS(ml_matrix x, double t), ml_matrix &x, double h, double t)
4th order Runge-Kutta integration algorithm with time as a RHS input
ml_matrix rk4 (ml_matrix RHS(ml_matrix x, double t, void *context), ml_matrix &x, double h, double t, void *context)
4th order Runge-Kutta integration algorithm with time as a RHS input and a context pointer
ml_matrix rk4 (ml_matrix RHS(ml_matrix &x, ml_matrix &a), ml_matrix &x, double h, ml_matrix a)
4th order Runge-Kutta integration algorithm with a matrix input to the RHS
double pss_rem (double x, double y)
Remainder function.
double fix (double x)
Round to 0.
double r2p5 (double x)
Round to nearest 0.5.
int sct_sign (double x)
Determine sign of number and return unitary value.
double sct_max (double a, double b)
Find maximum of two numbers.
double unwrap (double angle)
Unwrap radian values to (-pi,pi) interval.
ml_matrix intersect_line_ellipsoid (const ml_matrix &p, const ml_matrix &u, const ml_matrix &e)
Find the intersection between a line and an ellipsoid.
ml_matrix intersect_line_sphere (const ml_matrix &p, const ml_matrix &u, double r)
Find the intersection between a line and an sphere.
ml_matrix p_gauss (int nMax, int mMax, double theta, ml_matrix &dp)
Computes the Gaussian form of the Legendre functions and the first derivatives.
void s_c_harm (const ml_matrix &a, int n, ml_matrix &s, ml_matrix &c)
Generate a series of sine and cosine harmonics.
void c_to_d_zoh (const ml_matrix &a, const ml_matrix &b, double dT, ml_matrix &aD, ml_matrix &bD)
Compute a discrete-time linear system from a continuous system.
ml_matrix expm (const ml_matrix &a)
Compute the matrix exponential (of a square matrix only) using a power series expansion.
double WrapPhase (double angle)
Wrap a phase angle to keep its value between -pi and +pi.
ml_matrix WrapPhase (ml_matrix angle)
Wrap a vector of phase angles to keep their values between -pi and +pi.
ml_matrix UnwrapPhase (ml_matrix theta)
Unwrap a vector of angular values so they change continuously instead of wrapping.
ml_matrix diff (ml_matrix a)
Compute the difference between successive elements of a 1-D vector.
ml_matrix delt_circ (ml_matrix x, ml_matrix y)
Compute a delta in circular coordinates.
ml_matrix circle_fit (ml_matrix x, ml_matrix y)
Compute a delta in circular coordinates.
double factorial (double n)
Compute a factorial.
double interp_2d (ml_matrix a, ml_matrix x, ml_matrix y, double xK, double yK)
2D interpolation
double newton_raphson (double f(double x, void *context), double df(double x, void *context), double x0, double tol, int nMax, void *context)
1 dimensional root finder
double secant (double RHS(double x, void *context), double x0, double x00, double tol, int nMax, void *context)
1 dimensional root finder
ml_matrix average_unit_vector (ml_matrix u1, ml_matrix u2)
Average unit vector.
ml_matrix pinv (ml_matrix a)
Pseudo inverse.
ml_matrix downhill_simplex (double RHS(const ml_matrix &x, void *context), ml_matrix &x, ml_matrix &options, void *context)
Downhill simplex.
ml_matrix orthogonalize (ml_matrix a)
Orthogonalize.
ml_matrix logistic (ml_matrix x)
Logistic function.
double logistic (double x)
Logistic function.
double interp_extrap_1d (ml_matrix a, ml_matrix x, double xK)
1D interpolation and extrapolation
double gaussian_multivariate_density (ml_matrix y, ml_matrix y_bar, ml_matrix P)
Gaussian Mulivariate Normal Distribution function.
ml_matrix roots_second_order (double a, double b, double c)
Roots second order.
ml_matrix roots_second_order (const ml_matrix &p)
Roots second order.
ml_matrix skew_symmetric (const ml_matrix &p)
Generate a skew symmetric matrix.
double trig_reduction (double a, double b, double c)
Solve for beta: a*sin(beta)+b*cos(beta) = c.
ml_matrix m_k_3_by_3 (const ml_matrix &m, int k)
Returns a 3x3 matrix from a 3x3*n matrix.
int intersect_line_sphere_true (const ml_matrix &p1, const ml_matrix &p2, double r)
Find if a line intersects a sphere.
ml_matrix append_diagonal (const ml_matrix &a, const ml_matrix &b)
Append a diagonal matrix to another matrix.
double trapezoidal_integration (double Integrand(double x, void *context), double a, double b, int n, void *context)
Trapezoidal integration.
double two_dimensional_integration (ml_matrix Integrand(const ml_matrix &x, const ml_matrix &y, void *context), double a, double b, double c, double d, int nX, int nY, void *context)
Two dimensional integration.
Detailed Description
Math utility functions.
Function Documentation
golden_section()
double golden_section (double RHSdouble x, void *context, double a, double b, double tol, int maxIts, void * context)
Golden section minimization.
Parameters
RHS Right-hand side function definition
a Left range
b Right range
tol Tolerance
maxIts Maximum number of interations
*context to data from RSH
Returns
minimum value of x
rk0()
ml_matrix rk0 (ml_matrix RHSml_matrix x, double t, void *context, ml_matrix & x, double h, double t, void * context)
0th order Runge-Kutta integration algorithm with time as a RHS input
0th order Runge-Kutta integration algorithm with time as a RHS input
RHS actually does the propagation
Parameters
RHS Right-hand side function definition
x Current state
h Integration time step
t Current time
*context Pointer to data to be passed to RHS
Returns
Derivative of x
rk4()
ml_matrix rk4 (ml_matrix RHSml_matrix x, double t, ml_matrix & x, double h, double t)
4th order Runge-Kutta integration algorithm with time as a RHS input
4th order Runge-Kutta integration algorithm with time as a RHS input
Parameters
RHS Right-hand side function definition
x Current state
h Integration time step
t Current time
Returns
Derivative of x
pss_rem()
double pss_rem (double x, double y)
Remainder function.
Remainder function.
Parameters
x Numerator
y Denominator
Returns
Remainder from the division of y into x
Referenced by delt_circ(), and r2p5().
fix()
double fix (double x)
Round to 0.
Round to 0.
Parameters
x Number to be rounded
Returns
Number rounded to 0
Referenced by jd_to_date().
r2p5()
double r2p5 (double x)
Round to nearest 0.5.
Round to nearest 0.5.
Parameters
x Number to be rounded
Returns
Number rounded to the nearest "point 5"
References pss_rem().
Referenced by jd_to_date(), and mean_sidereal_day().
sct_sign()
int sct_sign (double x)
Determine sign of number and return unitary value.
Determine sign of number and return unitary value.
Parameters
x Number
Returns
Unitary value, i.e. 1 or -1
Referenced by ImpulsiveManeuver(), InPlane(), OutOfPlane(), and Target().
sct_max()
double sct_max (double a, double b)
Find maximum of two numbers.
Find maximum of two numbers.
Parameters
a First number
b Second number
Returns
Maximum of a and b
unwrap()
double unwrap (double angle)
Unwrap radian values to (-pi,pi) interval.
Unwrap radian values to (-pi,pi) interval.
Parameters
angle Angle in radians
Returns
Unwrapped angle
References PI, and TWO_PI.
Referenced by PID3Axis::Update().
intersect_line_ellipsoid()
ml_matrix intersect_line_ellipsoid (const ml_matrix & p, const ml_matrix & u, const ml_matrix & e)
Find the intersection between a line and an ellipsoid.
Always returns the closest point. The line is defined by a point and unit vectors. Returns empty if there is no intersection
Parameters
p (3,1) Point
u (3,1) Unit vector
e (3,1) (a,b,c) semi-axes of ellipsoid
Returns
Intersection point
Referenced by intersect_line_sphere().
intersect_line_sphere()
ml_matrix intersect_line_sphere (const ml_matrix & p, const ml_matrix & u, double r)
Find the intersection between a line and an sphere.
Find the intersection between a line and an sphere.
Always returns the closest point. The line is defined by a point and unit vectors.
Parameters
p (3,1) Point
u (3,1) Unit vector
r (1,1) Radius of sphere
Returns
Intersection point
References intersect_line_ellipsoid().
p_gauss()
ml_matrix p_gauss (int nMax, int mMax, double theta, ml_matrix & dp)
Computes the Gaussian form of the Legendre functions and the first derivatives.
Computes the Gaussian form of the Legendre functions and the first derivatives.
Because there is no zero indexing in MATLAB, the P's are offset in the p matrix as follows:
n,m p(n+1,m+1) = P
MATLAB Form: [p, dP] = PGauss(nMax, mMax, theta)
References: Wertz, J., Spacecraft Attitude Determination and Control, Kluwer, 1976, pp. 781.
Parameters
nMax max value of first index
mMax max value of second index
theta input value (usually an angle in rads)
dp Matrix for derivative outputs dp(n,m) / d(theta)
Returns
p Gauss functions, P(n,m)
Referenced by mag_field().
s_c_harm()
void s_c_harm (const ml_matrix & a, int n, ml_matrix & s, ml_matrix & c)
Generate a series of sine and cosine harmonics.
Generate a series of sine and cosine harmonics.
Parameters
a Column vector (m,1) argument, in radians
n Number of harmonics
s Vector of sine harmonics output
c Vector of cosine harmonics output
Referenced by mag_field().
c_to_d_zoh()
void c_to_d_zoh (const ml_matrix & a, const ml_matrix & b, double dT, ml_matrix & f, ml_matrix & g)
Compute a discrete-time linear system from a continuous system.
Compute a discrete-time linear system from a continuous system.
Parameters
a Continuous matrix
b Continuous matrix
dT Time step (sec)
f Discrete matrix
g Discrete matrix
References expm().
Referenced by FFEccLinOrb(), LPCircular(), LPEccentricGVE(), and MonitoringAlg().
expm()
ml_matrix expm (const ml_matrix & a)
Compute the matrix exponential (of a square matrix only) using a power series expansion.
Parameters
a Square matrix
Returns
b Matrix exponential, b = exp(a)
Referenced by c_to_d_zoh().
WrapPhase() [1/2]
double WrapPhase (double angle)
Wrap a phase angle to keep its value between -pi and +pi.
*sctlib
Parameters
angle Phase angle [rad]
Returns
Phase angle wrapped between -PI and PI [rad]
References PI, and TWO_PI.
Referenced by add_elements(), CirclePhase(), El2Alfriend(), EllipsePhase(), FFEccGoals(), FFEccHills2Goals(), FFEccXExt(), FFEccYExt(), FFEccZExt(), GenerateTeamGoals(), InPlane(), MeanAnom2TrueLat(), MonitoringAlg(), OrbElemDiff(), orbit_acquisition_dv(), sub_elements(), and TargetTrueAnom().
WrapPhase() [2/2]
ml_matrix WrapPhase (ml_matrix angle)
Wrap a vector of phase angles to keep their values between -pi and +pi.
*sctlib
Parameters
angle Vector of phase angles with no limits. [rad]
Returns
wrapped Vector of phase angles wrapped between -PI and +PI. [rad]
References PI, and TWO_PI.
UnwrapPhase()
ml_matrix UnwrapPhase (ml_matrix angle)
Unwrap a vector of angular values so they change continuously instead of wrapping.
*sctlib
Parameters
angle Vector of angular values. [rad]
Returns
unwrapped New vector with jumps larger than 2*PI in magnitude removed so that it changes "continuously". [rad]
References diff(), PI, and TWO_PI.
Referenced by DeltaEl2AlfriendMat(), FFEccDiscreteHills(), GenerateTimeVector(), ImpulsiveLPManeuver(), LPEccentric(), LPEccentricGVE(), and MonitoringAlg().
diff()
ml_matrix diff (ml_matrix a)
Compute the difference between successive elements of a 1-D vector.
Compute the difference between successive elements of a 1-D vector.
Parameters
a 1-dimensional matrix, length N
Returns
b 1-dimensional matrix, ith element is a(i+1)-a(i), length N-1
Referenced by AccelVector2ManeuverStruct(), DeltaEl2AlfriendMat(), FFEccDiscreteHills(), FFEccEstimateCost(), FFEccXExt(), FFEccYExt(), FFEccZExt(), ImpulsiveLPManeuver(), LPEccentricGVE(), LPEccentricTimeWeight(), MonitoringAlg(), NearestOffset(), OptimalAssignment(), and UnwrapPhase().
delt_circ()
ml_matrix delt_circ (ml_matrix x, ml_matrix y)
Compute a delta in circular coordinates.
Compute a delta in circular coordinates.
It does not check dimensions.
Parameters
x 2-dimensional matrix
y 2-dimensional matrix
Returns
z 2-dimensional matrix
References PI, and pss_rem().
circle_fit()
ml_matrix circle_fit (ml_matrix x, ml_matrix y)
Compute a delta in circular coordinates.
Compute a delta in circular coordinates.
Parameters
x column matrix
y column matrix
Returns
s column matrix [a;b;r]
pinv()
ml_matrix pinv (ml_matrix a)
Pseudo inverse.
Pseudo inverse.
Parameters
a matrix
Returns
orthogonal matrix
Referenced by az_el_range_range_rate_to_rv(), camera_calibration(), momentum_unloading(), and q_from_u().
downhill_simplex()
ml_matrix downhill_simplex (double RHSconst ml_matrix &x, void *context, ml_matrix & x, ml_matrix & options, void * context)
Downhill simplex.
Parameters
RHS Function to minimize
x Initial guess
options Options
context Context pointer to pass to RHS
Referenced by fit_PSF_to_data().
orthogonalize()
ml_matrix orthogonalize (ml_matrix a)
Orthogonalize.
Orthogonalize.
Orthogonalize a 3x3 matrix
Parameters
a matrix
Returns
orthogonal matrix
Referenced by camera_calibration(), and q_from_u().
logistic() [1/2]
ml_matrix logistic (ml_matrix x)
Logistic function.
Parameters
x input
Returns
1/(1+exp(-x))
logistic() [2/2]
double logistic (double x)
Logistic function.
Parameters
x input
Returns
1/(1+exp(-x))
interp_extrap_1d()
double interp_extrap_1d (ml_matrix a, ml_matrix x, double xK)
1D interpolation and extrapolation
1D interpolation and extrapolation
Parameters
a array of values
x corresponding x value
xK value of interest
Returns
value
gaussian_multivariate_density()
double gaussian_multivariate_density (ml_matrix y, ml_matrix y_bar, ml_matrix P)
Gaussian Mulivariate Normal Distribution function.
Gaussian Mulivariate Normal Distribution function.
Parameters
y array of parameters
y_bar corresponding means
P covariance matrix
Returns
likelihood
roots_second_order() [1/2]
ml_matrix roots_second_order (double a, double b, double c)
Roots second order.
Roots second order.
Parameters
a Coefficient
b Coefficient
c Coefficient
Returns
roots
Referenced by roots_second_order().
roots_second_order() [2/2]
ml_matrix roots_second_order (const ml_matrix & p)
Roots second order.
Roots second order.
Parameters
p array of coefficients
Returns
roots
References roots_second_order().
skew_symmetric()
ml_matrix skew_symmetric (const ml_matrix & v)
Generate a skew symmetric matrix.
Generate a skew symmetric matrix.
Parameters
v Vector (3x1)
Returns
skew symmetric matrix
Referenced by attitude_propagation_discrete(), discrete_state_transition_matrix(), multi_body_central_hub_with_rwa::state_derivative(), and multi_body_central_hub::state_derivative().
trig_reduction()
double trig_reduction (double a, double b, double c)
Solve for beta: a*sin(beta)+b*cos(beta) = c.
Parameters
a Coefficient
b Coefficient
c RHS
Returns
roots
m_k_3_by_3()
ml_matrix m_k_3_by_3 (const ml_matrix & m, int k)
Returns a 3x3 matrix from a 3x3*n matrix.
Parameters
m 3x3*n matrix
k index
Returns
3x3 matrix
Referenced by multi_body_central_hub_with_rwa::state_derivative(), and multi_body_central_hub::state_derivative().
intersect_line_sphere_true()
int intersect_line_sphere_true (const ml_matrix & p1, const ml_matrix & p2, double r)
Find if a line intersects a sphere.
Find if a line intersects a sphere.
Parameters
p1 3x1 origin point on the sphere
p2 3x1 final point off the sphere
r Radius of sphere
Returns
3x3 matrix
append_diagonal()
ml_matrix append_diagonal (const ml_matrix & a, const ml_matrix & b)
Append a diagonal matrix to another matrix.
Append a diagonal matrix to another matrix.
Parameters
a square matrix
b diagonal of a matrix
Returns
Combined matrix
trapezoidal_integration()
double trapezoidal_integration (double Integranddouble x, void *context, double a, double b, int n, void * context)
Trapezoidal integration.
Trapezoidal integration.
Referenced by rhs_airy_defocused_psf().
two_dimensional_integration()
double two_dimensional_integration (ml_matrix Integrandconst ml_matrix &x, const ml_matrix &y, void *context, double a, double b, double c, double d, int nX, int nY, void * context)
Two dimensional integration.
Two dimensional integration.
Parameters
Integrand pointer to the integrand function
a Minimum x
b Maximum x
c Minimum y
d Maximum y
nX Number of divisions in x
nY Number of divisions in y
*context Pointer to data to pass to Integrand
Returns
Integral value
Referenced by imager_psf(), and imager_psf_uint16().