Spacecraft Control Framework: sc_lambert.h File Reference
sc_lambert.h File Reference
Control
Lambert method.
Classes
struct lambert
Lambert orbital element starting and ending set.
Functions
bool Target (double t0, double tTrans, const lambert d, ml_matrix &vTrans, ml_matrix &deltaV)
Perform targeting between two orbits.
ml_matrix Lambert (const ml_matrix &r1, const ml_matrix &r2, double dT, int tM, double mu, double &a, double &p, int maxIter=10, double tol=1e-10)
double Zeta (double x)
double CubicRoot (double h1, double h2)
Detailed Description
Lambert method.
Function Documentation
Target()
bool Target (double t0, double tTrans, const lambert d, ml_matrix & vTrans, ml_matrix & deltaV)
Perform targeting between two orbits.
Uses rv_orb_gen to propagate the first orbit to t0 and the second orbit to t0+tTrans. Chooses the long or short was based on angular momentum and computes the Lambert solution. Finally, checks for a hit Earth condition.
Parameters
t0 Start time
tTrans Transfer time
d Lambert structure with two sets of orbital elements
vTrans The resulting transfer velocities (3x2)
deltaV The resulting delta-V's (3x2)
Returns
A flag indicating a feasible transfer was found that doesn't hit the Earth
References lambert::el1, lambert::el2, Lambert(), MU_EARTH, rv_orb_gen(), and sct_sign().
Lambert()
ml_matrix Lambert (const ml_matrix & r1, const ml_matrix & r2, double dT, int tM, double mu, double & a, double & p, int maxIter, double tol)
Solves the Lambert time of flight problem using Battin's method.
MATLAB Form:
[vT, a, p, tol] = Lambert(r1, r2, dT, tM, tol, maxIter)
Parameters
r1 (3,1) Initial position vector
r2 (3,1) Final position vector
dT Time between position 2 and 1
tM direct (1) or retrograde (-1)
mu Gravitational parameter
a Resulting semi-major axis of the trajectory
p Resulting parameter for the orbit
Returns
Matrix (3,2) Transfer velocity
References: Battin, R. H. "An Introduction to the Mathematics and Methods of Astrodynamics", AIAA Education Series.
Vallado, D. A. Fundamentals of Astrodynamics and Applications.
References PI.
Referenced by lambert_tof(), and Target().