Spacecraft Control Framework: sc_utility.h File Reference
sc_utility.h File Reference
Utilities
Miscellaneous functions.
Macros
#define ERROR(...) error(__FILE__,__LINE__,__VA_ARGS__)
Macro for calling error() with file and line information.
Functions
unsigned short GrayToBinary (unsigned short x)
Converts gray code to binary.
unsigned short BinaryToGray (unsigned short x)
Converts binary to gray code.
ml_matrix unique_numbers_in_list (const ml_matrix &u)
Unique numbers in a list.
ml_matrix polygon_props (const ml_matrix &v, ml_matrix f, ml_matrix &n, ml_matrix &r)
Polygon properties for a set of polygons.
double polygon (const ml_matrix &v, ml_matrix &n, ml_matrix &r)
Polygon properties for a single polygon.
int get_naif_code (const char *s)
Get NAIF code.
double attitude_maneuver_time (double inertia, double torque, double angle, double momentum_max)
Attitude maneuver time.
void sc_log (const char *format,...)
Log an informational message to stdout.
void sc_warn (const char *format,...)
Log a message to stderr.
void sc_error (const char *file, int line, const char *format,...)
Throw a runtime exception, halting execution of the app (if not caught) and printing an error message.
Detailed Description
Miscellaneous functions.
Function Documentation
GrayToBinary()
unsigned short GrayToBinary (unsigned short x)
Converts gray code to binary.
Parameters
x gray code.
Returns
binary.
BinaryToGray()
unsigned short BinaryToGray (unsigned short x)
Converts binary to gray code.
Converts binary to gray code.
Parameters
x binary.
Returns
gray code.
unique_numbers_in_list()
ml_matrix unique_numbers_in_list (const ml_matrix & u)
Unique numbers in a list.
Unique numbers in a list.
Parameters
u row matrix
Returns
row matrix containing unique numbers.
polygon_props()
ml_matrix polygon_props (const ml_matrix & v, ml_matrix f, ml_matrix & n, ml_matrix & r)
Polygon properties for a set of polygons.
Polygon properties for a set of polygons.
Parameters
v nx3 matrix of vectors
f mxp matrix of faces holding indexes to v
n return normals 3xm
f return position vectors 3xm
Returns
area 1xm
References polygon().
Referenced by aero_newtonian::initialize().
polygon()
double polygon (const ml_matrix & v, ml_matrix & n, ml_matrix & r)
Polygon properties for a single polygon.
Polygon properties for a single polygon.
Parameters
v 3xn matrix of vectors
n return normals 3x1
r return position vector 3x1
Returns
area
Referenced by polygon_props().
get_naif_code()
int get_naif_code (const char * s)
Get NAIF code.
Get NAIF code.
The input is assumed to be lower case
Parameters
s string
Returns
naif code
Referenced by planet_ecliptic_to_orbit().
attitude_maneuver_time()
double attitude_maneuver_time (double inertia, double torque, double angle, double momentum_max)
Attitude maneuver time.
Attitude maneuver time.
UNFINISHED.
Parameters
inertia axis inertia
torque maximum torque
angle desired angle
momentum_max maximum allowable momentum
Returns
Time