PSS Common Module: Core/Common/Database/MergeConstantDB.m File Reference
MergeConstantDB.m File Reference
uiwait
Functions
function MergeConstantDB (in action, in a, in b)
Merges b into a using a GUI.
function CreateGUI ()
no change needed
function NextConstant (in k0, in x, in y, in j, in h)
The figure window.
Detailed Description
uiwait
PSS internal file version information
Date
2018-11-07
Revision
1b2c79680ac913c983d4ea22aa8067b3c5264a45
Merges b into a using a GUI. The new file is saved as "NewDB.mat".
Function Documentation
CreateGUI()
function CreateGUI ()
no change needed
Copyright (c) 1999, 2008 Princeton Satellite Systems, Inc. All rights reserved.
replace value in a with that in b
Initialize the display
References Constant(), MergeConstantDB(), and Select().
NextConstant()
function NextConstant (in k0, in x, in y, in j, in h)
The figure window.
PSS Logo
Display next constant mismatch