ControlDeck: cd_control_system Class Reference
cd_control_system Class Reference
[ControlDeck framework]
The system class which manages a set of modules.
#include <cd_control_system.h>
Public Member Functions
cd_control_system (const char *system_name)
Create a system with the given name.
bool add_control_module (cd_control_module *module)
Add a module to the system.
void remove_control_module (const char *name)
Remove a module from the system.
void initialize_data ()
void initialize ()
Detailed Description
The system class which manages a set of modules.
A control deck consists of a number of modules, which can be grouped into systems. Each module can belong to one system. Users will not ordinarily interact with systems directly unless you are creating a control deck without a setup file.
Member Function Documentation
void cd_control_system::initialize ()
Initialize all the loaded modules. Calls each module's initialize_data_requests and initialize functions.
References cd_control_module::initialize(), and cd_control_module::initialize_data_requests().
void cd_control_system::initialize_data ()
Initialize the data for all the loaded modules. Calls each module's execute_setups and initialize_data functions.
References cd_control_module::execute_setups(), and cd_control_module::initialize_data().
The documentation for this class was generated from the following files:
cd_control_system.h
cd_control_system.cc